
#A variável base guarda dados em forma de lista
#Respectivamente: string com uma mensagem e descrição
#quanto à satisfação

base = [('Produto muito bom', 'satisfeito'),
        ('Gostei muito do produto', 'satisfeito'),
        ('Produto maravilhoso', 'satisfeito'),
        ('Que produto bonito', 'satisfeito'),
        ('Abaixo do esperado', 'insatisfeito'),
        ('Não gostei', 'insatisfeito'),
        ('Desbotou na primeira semana', 'insatisfeito'),
        ('Olha só esse produto', 'satisfeito'),
        ('Material de baixa resistência', 'insatisfeito'),
        ('Custo beneficio excelente', 'satisfeito'),
        ('A foto é diferente do produto', 'insatisfeito'),
        ('É retrocompatível com todas as gerações', 'satisfeito'),
        ('A estrutura foi desenvolvida de forma bem estratégica', 'satisfeito'),
        ('É compacto, relativamente pequeno, e não pesa muito', 'satisfeito'),
        ('Não faz barulho algum', 'satisfeito'),
        ('Suporte confuso e trabalhoso', 'insatisfeito'),
        ('Amei e não consigo mais me ver sem', 'satisfeito'),
        ('Design feio, parece uma caixa de som', 'insatisfeito'),
        ('Muito barulhento, incomoda bastante', 'insatisfeito'),
        ('Feio e barulhento', 'insatisfeito'),
        ('Produto veio conforme as especificações', 'satisfeito'),
        ('Recebi o produto em ótimo estado', 'satisfeito'),
        ('Produto muito caro', 'insatisfeito'),
        ('O produto ultrapassa as expectativas', 'satisfeito'),
        ('Produto pouco protegido', 'insatisfeito'),
        ('Atende bem as expectativas', 'satisfeito'),
        ('Me arrependi de comprar', 'insatisfeito'),
        ('Material de baixa qualidade', 'insatisfeito'),
        ('Não é confortável', 'insatisfeito'),
        ('Depois de algum tempo usando começa a incomodar', 'insatisfeito'),
        ('Corresponde ao anunciado', 'satisfeito'),
        ('Bateria dura pouco', 'insatisfeito'),
        ('Não tem microfone, não tem giroscópio, não tem auto-falante', 'insatisfeito'),
        ('Não é muito funcional', 'insatisfeito'),
        ('Superou as expectativas', 'satisfeito'),
        ('Sensacional o produto', 'satisfeito'),
        ('Produto premium de ótimo material', 'satisfeito'),
        ('Produto nada impressionante', 'insatisfeito'),
        ('Não achei o produto interessante', 'insatisfeito'),
        ('Produto não impressiona', 'insatisfeito'),
        ('Veio com defeito', 'insatisfeito'),
        ('É uma boa opção', 'satisfeito'),
        ('Não espere muito', 'insatisfeito'),
        ('Vale muito a pena', 'satisfeito'),
        ('Vale a pena', 'satisfeito'),
        ('Não vale a pena', 'insatisfeito'),
        ('Produto com pouco tempo de garantia', 'insatisfeito'),
        ('Não recomendo a compra', 'insatisfeito'),
        ('Atendimento ruim', 'insatisfeito'),
        ('Ótimo investimento', 'satisfeito'),
        ('Apresentou falhas', 'insatisfeito'),
        ('Apresentou muitos travamentos', 'insatisfeito'),
        ('Trava muito', 'insatisfeito'),
        ('Muitos bugs', 'insatisfeito'),
        ('Apresentou muitos bugs', 'insatisfeito'),
        ('Dá problemas com frequência', 'insatisfeito'),
        ('Esse foi o pior', 'insatisfeito'),
        ('Funciona muito bem', 'satisfeito'),
        ('Detestei, lerdo pra tudo', 'insatisfeito'),
        ('Extremamente desapontada', 'insatisfeito'),
        ('Produto muito robusto', 'satisfeito'),
        ('Entrega com atraso', 'insatisfeito'),
        ('Prometeu e não entregou nenhuma qualidade', 'insatisfeito'),
        ('O preço é meio proibitivo', 'insatisfeito'),
        ('Não vai se arrepender', 'satisfeito'),
        ('Não me arrependo', 'satisfeito'),
        ('Não fiquei arrependido', 'satisfeito'),
        ('Não tenho o que reclamar', 'satisfeito'),
        ('Sem nenhuma reclamação', 'satisfeito'),
        ('Sem defeitos', 'satisfeito'),
        ('Zero defeitos', 'satisfeito'),
        ('Vale a pena comprar', 'satisfeito'),
        ('Vale muito a pena comprar', 'satisfeito'),
        ('Ótima ergonomia', 'satisfeito'),
        ('Produto muito ergonômico', 'satisfeito'),
        ('Fácil manuseio', 'satisfeito'),
        ('Difícil manuseio', 'insatisfeito'),
        ('Nenhuma dificuldade para manusear', 'satisfeito'),
        ]